# Logo
logo: images/logo.png # Empty this to unset logo and show site title in the same place

# Header
menu:
  Home: .
  Archives: archives
  Categories: categories
  Tags: tags
  About: about

# Content
excerpt_link: Read more
fancybox: true

# Profile
profile: true # Whether to show profile bar
gravatar: false # Whether to use gravatar with the email. If you do, put your email address in your site's `_config.yml`.

# Sidebar
sidebar: right # set to false if you don't want a sidebar
widgets:
- recent_posts
- category
- tag
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  github: http://github.com/PhiLhoSoft
  twitterEN: https://twitter.com/PhiLhoSoft
  stackoverflow: http://stackoverflow.com/users/15459/philho
  deviantart: http://philho.deviantart.com/
  free: http://Phi.Lho.free.fr/
  twitterFR: https://twitter.com/Phi_Lho
  goodreads: https://www.goodreads.com/review/list/3585303-philippe-lhoste
  rss: atom.xml

about: A blog where I share my technical (programming) findings, insights, experiences, tutorials, etc.

# Links
links:
  Hexo: http://hexo.io

# CDN
cdn: # You can choose "useso" instead of "google apis"(default).
# cdn: useso
# OR
# cdn:

# Miscellaneous
google_site_verification:
google_analytics: UA-20636309-2
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
